# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define "icaro"
  config.vm.box = "centos/7"
  config.vm.hostname = "icaro"

  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.network "public_network"

  config.vm.provider "virtualbox" do |vitualbox|
  end

  config.vm.provider :digital_ocean do |provider, override|
    override.ssh.private_key_path = '~/.ssh/id_rsa'
    override.vm.box = 'digital_ocean'
    override.vm.box_url = "https://github.com/devopsgroup-io/vagrant-digitalocean/raw/master/box/digital_ocean.box"

    provider.token = 'YOUR TOKEN'
    provider.ssh_key_name = 'YOUR KEY NAME'
    provider.image = 'centos-7-x64'
    provider.region = 'lon1'
    provider.size = '512mb'
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
  end

end
