# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define "icaro"
  config.vm.box = "centos/7"

  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.network "forwarded_port", guest: 443, host: 8080
  config.vm.network "forwarded_port", guest: 80, host: 8081

  config.vm.provider "virtualbox" do |vitualbox|
  end

  config.vm.provider :digital_ocean do |provider, override|
    override.ssh.private_key_path = '~/.ssh/id_rsa'
    override.vm.box = 'digital_ocean'
    override.vm.box_url = "https://github.com/devopsgroup-io/vagrant-digitalocean/raw/master/box/digital_ocean.box"

    provider.token = 'YOUR TOKEN'
    provider.ssh_key_name = 'YOUR KEY NAME'
    provider.image = 'centos-7-x64'
    provider.region = 'lon1'
    provider.size = '1gb'
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
    ansible.groups = {
      "icaro" => ["icaro"],
      "sun" => ["icaro"],
      "wax" => ["icaro"],
      "icarodb" => ["icaro"]
    }
  end

end
