#!/bin/sh
OPT=$1
shift
source /opt/icaro/dedalo/config

case "$OPT" in
    query)
        /usr/sbin/chilli_query -s /var/run/dedalo/chilli.sock "$@"
    ;;
    config)
        /opt/icaro/dedalo/template/engine /opt/icaro/dedalo/template/chilli.conf.tpl
        if [ $? -eq 0 ]; then
            echo "Configuration generated successfully"
        else
            echo "Error on configuration generating"
        fi
    ;;
    start)
            systemctl start dedalo
    ;;
    restart)
            systemctl restart dedalo
    ;;
    stop)
            systemctl stop dedalo
    ;;
    status)
            systemctl status dedalo
    ;;
    info)
        echo "Dedalo: Network Access Controller"
        echo -e "  HotSpot:\t$HS_ID"
        echo -e "  Unit name:\t$HS_UNIT_NAME"
        echo -e "  UUID:\t\t$HS_UUID"
        echo -e "  Secret:\t$HS_SECRET"
        echo -e "  MAC:\t\t$(cat /sys/class/net/$HS_INTERFACE/address | tr ':' '-' | awk '{print toupper($0)}')"
    ;;
    *)
        echo "Usage: $0 { query | config | start | stop | restart | status | info }"
esac