name: Trivy Security Scan
on:
  push:
    branches: [ main, master ]
  release:
    types: [ created ]

jobs:
  trivy-scan:
    name: Trivy Security Scan
    runs-on: ubuntu-latest
    permissions:
      contents: write
      security-events: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      # Verify that the release tag belongs to the main branch (main or master)
      - name: Verifica tag release
        if: github.event_name == 'release'
        id: verify-tag
        run: |
          # Gets the branches containing the current tag's commit
          BRANCHES_WITH_TAG=$(git branch -a --contains ${{ github.ref_name }})

          if echo "$BRANCHES_WITH_TAG" | grep -q -E "(main|master)"; then
            echo "valid_tag=true" >> $GITHUB_OUTPUT
          else
            echo "valid_tag=false" >> $GITHUB_OUTPUT
            echo "::warning::Release tag not created from a main branch (main or master)"
          fi

      - name: Run Trivy vulnerability scanner
        if: github.event_name != 'release' || steps.verify-tag.outputs.valid_tag == 'true'
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: 'fs'
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH,MEDIUM,LOW'

      - name: Upload Trivy scan results to GitHub Security tab
        if: github.event_name != 'release' || steps.verify-tag.outputs.valid_tag == 'true'
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'

      - name: Update GitHub Dependency Graph
        if: github.event_name != 'release' || steps.verify-tag.outputs.valid_tag == 'true'
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: 'fs'
          format: 'github'
          output: 'dependency-results.json'

      - name: Generate CycloneDX SBOM
        if: github.event_name == 'release' && steps.verify-tag.outputs.valid_tag == 'true'
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: 'fs'
          format: 'cyclonedx'
          output: 'sbom.cdx.json'

      - name: Upload SBOM to Release
        if: github.event_name == 'release' && steps.verify-tag.outputs.valid_tag == 'true'
        uses: softprops/action-gh-release@v2.2.2
        with:
          files: sbom.cdx.json
